# .github/workflows/netlify.yml
name: Netlify Deploy Preview
on:
  push:
    paths-ignore:
      - '**.md'
      - 'examples'
      - '!examples/monaco-graphql-webpack'
  pull_request:
    types: [opened, synchronize]
  
jobs:
  graphiql-preview:
    name: "GraphiQL"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn Install
        uses: bahmutov/npm-install@v1
      # ( Build to ./dist or other directory... )
      - name: Build 
        run: yarn build

      - name: Build Bundles 
        run: yarn build-bundles

      - name: Build Typedoc
        run: yarn build-docs

      - name: Deploy Dev to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './packages/graphiql/'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Preview for GraphiQL"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          functions-dir: functions
          github-deployment-environment: "GraphiQL Deploy Preview"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        timeout-minutes: 1
  monaco-preview:
    name: "Monaco GraphQL"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn Install
        uses: bahmutov/npm-install@v1
      # ( Build to ./dist or other directory... )
      - name: Build 
        run: yarn build

      - name: Build Monaco Example 
        run: yarn workspace monaco-graphql-webpack run build

      - name: Deploy Monaco GraphQL Example to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './examples/monaco-graphql-webpack/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy Preview for Monaco"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          functions-dir: functions
          github-deployment-environment: "Monaco GraphQL Preview"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        timeout-minutes: 1
